Repository dyrpit/orderly-ai-1, pull requests merged in 2023-09, with the labels that each got.

#100 Feature/91 create file export handler
  src/components/navbar/FileExportAlert.tsx
  src/components/navbar/FileImportModal.tsx
  src/components/navbar/MobileMenu.tsx
  src/components/navbar/Navbar.tsx
Labels: feature

#101 chore: added app title and favicon, added alternative texts to images
  index.html
  src/assets/favicon.svg
  src/components/buttons/GenericButton.tsx
  src/components/navbar/DropdownStyles.ts
  src/components/navbar/Navbar.tsx
Labels: feature

#103 Feature/76 save redux store changes after page reload
  package-lock.json
  package.json
  src/components/navbar/DropdownMenu.tsx
  src/components/navbar/FileExport.tsx
  src/components/navbar/Navbar.tsx
  src/redux/store.tsx
Labels: feature

#104 feature/48-create-add-new-product-component #48
  src/components/addNewProduct/AddNewProduct.tsx
  src/components/addNewProduct/addnewProductStyle.ts
Labels: feature

#111 Refactor/108 re render component instead of page refresh
  src/components/admin-panel/AdminPanel.tsx
  src/components/form/LoginAndRegisterForm.tsx
  src/components/navbar/DropdownMenu.tsx
  src/components/navbar/Navbar.tsx
  src/redux/features/user/userSlice.ts
  src/redux/store.tsx
Labels: refactor

#116 fix: fixed bugs and cleaned the code
  src/components/admin-panel/AdminPanel.tsx
  src/components/navbar/Navbar.tsx
Labels: bug

#117 fix/72-generate-random-colors-for-new-category-bg#72
  package-lock.json
  src/components/newCategory/BackgroundColorPicker.tsx
Labels: bug

#120 refactor/110-rewrite-main-layout #110
  src/components/addNewProduct/AddNewProduct.tsx
  src/components/admin-panel/AdminPanel.tsx
  src/components/footer/Footer.tsx
  src/components/hero/Breadcrumb.tsx
  src/components/hero/CategoryItem.tsx
  src/components/navbar/DropdownMenu.tsx
  src/components/navbar/Navbar.tsx
  src/components/navbar/NavbarStyles.ts
  src/components/productCard/ProductCard.tsx
  src/components/productsList/ProductsList.tsx
  src/layout/MainLayout.tsx
Labels: refactor

#124 fix/123-add-min-h-for-mainlayout-on-mobile #123
  src/layout/MainLayout.tsx
Labels: bug

#125 fix: fixed bug with changing user's role
  src/components/admin-panel/AdminPanel.tsx
Labels: bug

#126 fix: hid 'Load data' button when any file is not selected, added toas…
  src/components/navbar/FileImportModal.tsx
Labels: bug

#128 fix: resolved all project errors
  src/components/addNewProduct/AddNewProduct.tsx
  src/components/addNewProduct/ProductDetailRadio.tsx
  src/components/form/LoginAndRegisterForm.tsx
  src/components/navbar/DropdownMenu.tsx
  src/components/navbar/FileExport.tsx
  src/components/navbar/MobileMenu.tsx
  src/components/navbar/Navbar.tsx
  src/components/newCategory/CategoryForm.tsx
  src/components/newCategory/CircleColorButton.tsx
  src/redux/features/categories/categoriesSlice.ts
  src/redux/features/products/productsSlice.ts
Labels: bug

#130 feature/105-add-category-edition-and-deletion #78 #105
  src/components/hero/CategoryItem.tsx
  src/hooks/reduxHooks/useEditCategoryName.ts
  src/redux/features/categories/categoriesSlice.ts
  src/redux/features/products/productsSlice.ts
Labels: feature

#131 feature/96-add-chakra-avatar-to-navbar #96
  src/components/form/LoginAndRegisterForm.tsx
  src/components/navbar/DropdownMenu.tsx
  src/redux/features/user/userSlice.ts
Labels: feature

#133 fix: restored overwritten changes
  src/components/admin-panel/AdminPanel.tsx
Labels: bug

#134 fix: routing with parameter
  src/App.tsx
  src/components/admin-panel/AdminPanel.tsx
  src/components/hero/Breadcrumb.tsx
  src/components/hero/CategoryItem.tsx
Labels: bug

#140 fix: changed users api url
  package-lock.json
  package.json
  src/util/api-calls.ts
  src/util/constants.ts
Labels: bug

#141 Feature/page not found
  src/App.tsx
  src/assets/no-page.svg
  src/components/no-page/PageNotFound.tsx
Labels: feature

#147 fix/138-make-navbar-sticky-on-mobile #138
  src/components/navbar/Navbar.tsx
  src/layout/MainLayout.tsx
Labels: bug

#148 feature/81-protect-routes-from-regular-and-unlogged-user #81
  src/components/addNewProduct/AddNewProduct.tsx
  src/components/newCategory/CategoryForm.tsx
Labels: feature

#150 fix: hide auth route for logged users
  src/components/form/LoginAndRegisterForm.tsx
Labels: bug

#152 fix: show new user in admin panel
  src/components/admin-panel/AdminPanel.tsx
Labels: bug

#155 feat: add delete confirmation for category delete
  src/components/hero/CategoryItem.tsx
Labels: feature

#157 feature/156-create-custom-switch-for-chatgpt-api-call-handle #156
  src/components/navbar/AiSwitch.tsx
  src/components/navbar/MobileMenu.tsx
  src/components/navbar/Navbar.tsx
Labels: feature

#158 fix/139-add-uuid-for-new-category #139
  package-lock.json
  package.json
  src/components/newCategory/CategoryForm.tsx
Labels: bug

#161 feature/159-connect-openAI-with-switch #159 #149
  prompt.json
  src/components/buttons/GenericButton.tsx
  src/components/hero/Breadcrumb.tsx
  src/components/navbar/AiSwitch.tsx
  src/components/shared/LoadingSpinner.tsx
  src/layout/MainLayout.tsx
  src/redux/features/gpt/gptSlice.ts
  src/redux/store.tsx
  src/types/prompt.ts
  src/util/api-calls.ts
Labels: feature

#162 feature/135-create-expire-session-counter #135
  src/components/navbar/DropdownMenu.tsx
  src/components/sessionCounter/SessionCounter.tsx
  src/layout/MainLayout.tsx
  src/redux/features/adminPanel/adminPanelSlice.ts
  src/redux/features/user/userSlice.ts
Labels: feature

#164 refactor/163-delete-test-redux-route #163
  src/App.tsx
  src/components/test-Redux-functions/testRedux.tsx
Labels: feature

#166 refactor/165-apply-uuid-to-newProduct #165
  src/components/addNewProduct/AddNewProduct.tsx
  src/types/category.ts
  src/types/product.ts
Labels: refactor

#168 chore/94-update-package-json-file-before-deployment #94
  package.json
Labels: chore

#170 Fix/169 replace gpt prompt to public folder
  public/prompt.json
Labels: bug

#171 feat: added youtube preview and clickable website url
  prompt.json
  src/components/productCard/ProductCard.tsx
Labels: feature

#173 fix/172-delete-unused-component #172
  src/components/productCard/ProductCard.tsx
Labels: bug

#175 Chore/89 write super readme for project
  README.md
  images/AddProduct.png
  images/NewCategoryComponent.png
  images/Widok niezalogowanego.png
  images/WidokAdmina.png
  images/WidokProduktu.png
  images/WidokProduktów.png
  images/WidokZalogowanego.png
Labels: chore
